Remove mjCollisionTree check causing build error with emscripten
Not sure if this will cause any other problems or why it was causing the build to fail yet

```
/mujoco/src/engine/engine_collision_driver.c:210:18: error:
static assertion failed due to requirement 'sizeof(struct mjCollisionTree_ *) % sizeof(double) == 0':
mjCollisionTree has a different size from mjtNum
  210 |   _Static_assert(sizeof(mjCollisionTree*) % sizeof(mjtNum) == 0,
/mujoco/src/engine/engine_collision_driver.c:210:60: note: expression evaluates to '4 == 0'
1 error generated.
emmake: error: 'make' failed (returned 2)
```